instructions to compile proxybroker to shared executable
bluet/proxybroker2 pull request #95
Opened 2022-08-23 13:39 UTC by ziloka

Instructions for #31. 

The steps for macos should be the same.
For windows it should be very similar the end of the `$(which proxybroker)` should be replaced with the location of the proxybroker script

2022-08-23 13:45 UTC, ziloka commented
the line in proxybroker/utils.py was stolen from [this stackoverflow comment](https://stackoverflow.com/a/44352931)

2022-08-23 13:55 UTC, bluet commented
@ziloka Is this for Linux/macOS or Windows also? AFAIK commands on Windows should be different, no?

It's OK if this is for Linux/macOS only, just change the PR title to clarify it. :-)

2022-08-23 14:27 UTC, ziloka commented
It works on windows too, I just don't have the develop environment on windows to test it because I usually work on Linux distributions.

2022-08-23 14:41 UTC, ziloka commented
> AFAIK commands on Windows should be different, no?

Yes they are different, which is why I stated that $(which proxybroker) needs to be replaced with the location of the python script

2022-08-23 15:11 UTC, ziloka commented
I think python 3.9 build is broken for windows when compiling. Here is the [error and the fix for it](https://stackoverflow.com/questions/64497319/python-discord-py-error-could-not-build-wheels-for-multidict-yarl-which-use)

2022-08-23 15:16 UTC, ziloka commented
Looking from [this github comment](https://github.com/Rapptz/discord.py/issues/5984#issue-731894511) it seems weird that the best solution is to not use python 3.9 on windows, or downgrade to python 3.8. I'm not sure about python 3.10

2022-08-23 16:53 UTC, ziloka commented
Okay just to note here 
> Because the program makes a temporary folder with a unique name, you can run multiple copies of the app; they won’t interfere > with each other. However, running multiple copies is expensive in disk space because nothing is shared.

> The _MEIxxxxxx folder is not removed if the program crashes or is killed (kill -9 on Unix, killed by the Task Manager on
> Windows, “Force Quit” on macOS). Thus if your app crashes frequently, your users will lose disk space to multiple _MEIxxxxxx > temporary folders.

> It is possible to control the location of the _MEIxxxxxx folder by using the [--runtime-tmpdir](https://pyinstaller.org/en/stable
> /usage.html#cmdoption-runtime-tmpdir) command line option. The specified path is stored in the executable, and the bootloader > will create the _MEIxxxxxx folder inside of the specified folder. Please see [Defining the Extraction Location](https://pyinstaller.org/en/stable/usage.html#defining-the-extraction-location) for details.
Running the program and it crashing it suddenly will cause users to lose disk space due to pyinstaller having to extract said files

2022-08-24 02:05 UTC, ziloka commented
Just curious, should we make automated builds to build executables for this project.

1. Just to know if the project can still be built with the changes made
2. People can just download them from github actions instead of compiling it themselves. For convenience sake?

2022-08-24 02:05 UTC, bluet commented
I've been in pure Linux env for over 15 years and don't have a Windows environment too. Actually, I can't say I know how to use it to develop or test python programs :rofl: 

Before we can confirm if it really works on Windows through testing all the functions, we can't say "It works". People might believe our words and waste lots of time following the instructions we provide, which only get errors lol

If making it work on Windows is difficult for now, we can reduce the scope of this PR to support just Linux/macOSX first (and review/merge it first). For the Windows support, you can create another PR and spend time digging deeper. :smiley:

2022-08-24 02:08 UTC, bluet commented
@ziloka auto-builds would be awesome. I just don't have the time (and knowledge, and passion) to figure out how to make windows builds. :smiling_face_with_tear: 

If you know how, PRs are welcome! :smiley:

2022-08-24 12:17 UTC, ziloka commented
alright

2022-08-24 17:31 UTC, ziloka commented
Okay so I dont think mac builds work either? https://github.com/ziloka/proxybroker2/runs/8000511714?check_suite_focus=true
RIght now it seems like Windows and Mac builds dont want to build which is kinda annoying.

2022-08-24 17:39 UTC, ziloka commented
From my research I honestly just think we should limit this PR to Linux only. Until I have some type of solution for windows and macOS.

2022-08-25 02:17 UTC, ziloka commented
Okay I have a solution for the other platforms and I think its just using a different tool for those platforms.

2022-08-25 02:38 UTC, ziloka commented
Nevermind I used the wrong flag (for whatever reason), and Linux and macOS builds are fine
https://github.com/ziloka/proxybroker2/runs/8007781077?check_suite_focus=true

2022-08-25 02:49 UTC, ziloka commented
Okay just to let you know, since I did a lot of research today, the reason why I can't make github actions build for windows is because of the project structure. It would honestly be better if there was a single python file that we wrote in side this project. Instead of generating that file and calling pyinstaller on it.

But I'm afraid to make a ton of reorganizing changes because I'm sure the project was structured like this for a reason.

2022-08-25 13:02 UTC, bluet commented
> Okay just to let you know, since I did a lot of research today, the reason why I can't make github actions build for windows is because of the project structure.
> It would honestly be better if there was a single python file that we wrote in side this project. 
Do you mean to combine EVERYTHING into ONE file?

> Instead of generating that file and calling pyinstaller on it.
I don't quite understand what you mean "generating that file".

> But I'm afraid to make a ton of reorganizing changes because I'm sure the project was structured like this for a reason.
Split different sets of codes into different files/modules will make it cleaner and easier to maintain, and they'll also be reusable.

2022-08-25 13:05 UTC, bluet commented
@ziloka BTW, #88 has been merged into `master` 3 days ago. Maybe you'd like to sync the changes back to your branch?

2022-08-25 13:37 UTC, ziloka commented
Oh im sorry i mean #94

2022-08-25 13:40 UTC, ziloka commented
> > Okay just to let you know, since I did a lot of research today, the reason why I can't make github actions build for windows is because of the project structure.
> > It would honestly be better if there was a single python file that we wrote in side this project.
> 
> Do you mean to combine EVERYTHING into ONE file?
> 
> > Instead of generating that file and calling pyinstaller on it.
> 
> I don't quite understand what you mean "generating that file".
> 
> > But I'm afraid to make a ton of reorganizing changes because I'm sure the project was structured like this for a reason.
> 
> Split different sets of codes into different files/modules will make it cleaner and easier to maintain, and they'll also be reusable.

I mean to explicitly have a command line .py file, instead of having setuptools generate that file. However im not sure if thats possible for a python application to be a library and a command line application while having a command line entrypoint that was written by programmers instead of having setup tools generate that file for us.

2022-08-25 16:49 UTC, ziloka commented
I think its ready

2022-08-25 17:39 UTC, ziloka commented
Alright, next time I will draft the PR instead of just like letting it be like this

2022-08-26 04:19 UTC, bluet requested changes

2022-08-26 04:19 UTC, bluet commented on README.md
> +
```suggestion

### Use pre-built Docker image
``` {.sourceCode .bash}
$ docker pull bluet/proxybroker2
```

```

2022-08-26 04:35 UTC, bluet commented
@ziloka would you like to also open another PR for the py-to-exe auto-build Actions? :rocket:

2022-08-26 21:20 UTC, ziloka commented
Okay I will

2022-08-27 01:03 UTC, ziloka commented
after thinking about this, i was being dumb about converting windows to exe, it just involves editing a bit more files, but I dont know if it interferes with it as a library.

2022-08-27 02:54 UTC, ziloka commented
https://github.com/ziloka/proxybroker2/runs/8047370449?check_suite_focus=true

2022-08-27 07:33 UTC, bluet commented
@ziloka cool.

BTW, something still need to be done in this PR, could you add WIP prefix in title?

2022-08-27 07:40 UTC, bluet commented
And could you check the content and format are correct?

I don't think people need to install binutils etc on Windows too lol

Also there's a missing _```_ at the end of docker part in README. I did have that in my previous code suggestions but maybe due to a bug in GitHub it's missing now.

2022-08-27 08:01 UTC, bluet submitted a review, later dismissed

2022-08-27 12:06 UTC, ziloka commented
Okay I think I fixed it now

2022-08-30 14:27 UTC, merged